DATA_FILE_PATH = 'scripts.txt'
MODEL_FILE_PATH = 'movie_script_model.keras'

SEQ_LENGTH = 50
BATCH_SIZE = 32
EPOCHS = 20
LAYER_SIZE = 128
DROPOUT_RATE = 0.2

SEED_TEXT = 'INT. DARK ROOM - NIGHT'
GENERATION_LENGTH = 1000
TEMPERATURE = 0.7